name: 'Add Markdown Feedback'
on:
  pull_request:
    paths: ['documentation/**.md']
    branches: ['main', 'release/6.x']

permissions:
  pull-requests: read

jobs:
  add-markdown-feedback:
    name: 'Add Markdown Feedback'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get base commit for the PR
        run: |
          git fetch origin ${{ github.base_ref }}
          echo "base_sha=$(git rev-parse origin/${{ github.base_ref }})" >> $GITHUB_ENV
          echo "Merging ${{ github.sha }} into ${{ github.base_ref }}"
      - name: Get changed files
        run: |
          echo "Files changed: '$(git diff-tree --no-commit-id --name-only -r ${{ env.base_sha }} ${{ github.sha }})'"
          changed_source_files=$(git diff-tree --no-commit-id --name-only -r ${{ env.base_sha }} ${{ github.sha }} | { grep "**.md$" || test $? = 1; })
          echo "Files to validate: '${changed_source_files}'"
          echo "updated_files=$(echo ${changed_source_files})" >> $GITHUB_ENV
      - name: Get dotnet version
        run: echo 'dotnet_version='$(jq -r '.tools.dotnet' global.json) >> $GITHUB_ENV

      - name: Append To File
        uses: kkeirstead/AppendToFile@main
        with:
          textToSearch: 'images/WasThisHelpful.png'
          textToAdd: '[<img src=/images/WasThisHelpful.png width="150"/>](https://www.surveymonkey.com/r/XFMFHJ9?src={insertFileName})'
          insertFileName: 'true'
          paths: ${{ env.updated_files }}

      - name: Generate artifacts
        run: |
          mkdir -p ./pr
          cp $GITHUB_EVENT_PATH ./pr/pr-event.json
          echo -n $GITHUB_EVENT_NAME > ./pr/pr-event-name
          git diff > ./pr/linter.diff
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: pr-linter
          path: pr/

      - name: Checkout
        uses: actions/checkout@v3
      # Download the artifact from the workflow that kicked off this one.
      # The default artifact download action doesn't support cross-workflow
      # artifacts, so use a 3rd party one.
      - name: 'Download linting results'
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: add-markdown-feedback.yml
          run_id: ${{github.event.workflow_run.id }}
          name: pr-linter
          path: ./pr-linter

      - name: 'Setup reviewdog'
        uses: reviewdog/action-setup@v1
      # Manually supply the triggering PR event information since when a PR is from a fork,
      # this workflow running in the base repo will not be given information about it.
      #
      # Also patch the fork's owner id in the event file, since reviewdog has as fail-fast path that
      # checks the head vs base repo owner id to determine if the PR is from a fork.
      # If so, it assumes that it doesn't have permissions to write comments on the PR.
      #
      # This isn't the case in our setup since we are using two workflows (lint-csharp and this one)
      # to enable write permissions on fork PRs.
      - name: Submit formatting suggestions
        run: |
          new_event_file=${{github.workspace}}/reviewdog_event.json
          new_event_name=$(cat ./pr-linter/pr-event-name)
          jq -j ".${new_event_name}.head.repo.owner.id = .${new_event_name}.base.repo.owner.id" ./pr-linter/pr-event.json > ${new_event_file}
          GITHUB_EVENT_NAME="${new_event_name}" GITHUB_EVENT_PATH="${new_event_file}" REVIEWDOG_GITHUB_API_TOKEN="${{ secrets.GITHUB_TOKEN }}" reviewdog \
              -name="AppendMarkdownFeedback" \
              -f=diff \
              -f.diff.strip=1 \
              -reporter="github-pr-review" \
              -filter-mode="nofilter" \
              -fail-on-error="true" \
              -level="warning" \
              < "./pr-linter/linter.diff"
