name: 'Check Learning Path Links'
on:
  pull_request:
    branches: ['main']

permissions:
  pull-requests: read
  
jobs:
  check-learning-path-links:
    name: 'Check Learning Path Links'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout merge
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
        with:
          persist-credentials: false
          path: merge
          
      - name: Checkout head
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
        with:
          persist-credentials: false
          ref: main
          path: head

      - name: Get base commit for the PR
        working-directory: ./merge
        run: |
          git fetch origin "$GITHUB_BASE_REF"
          base_sha=$(git rev-parse "origin/$GITHUB_BASE_REF")
          echo "base_sha=$base_sha" >> $GITHUB_ENV
          echo "Merging ${GITHUB_SHA} into ${GITHUB_BASE_REF}"

      - name: Get changed files
        working-directory: ./merge
        run: |
          trimmed_comment=$(echo "$COMMENT_BODY" | sed 's|/TODO ||I')
          mkdir -p ./issue
          echo -n "$trimmed_comment" > ./issue/issue-title
          echo -n "$COMMENT_URL" > ./issue/issue-url
          echo -n "$COMMENT_AUTHOR" > ./issue/issue-user
        env:
          COMMENT_BODY: ${{ github.event.comment.body }}
          COMMENT_URL: ${{ github.event.comment.html_url }}
          COMMENT_AUTHOR: ${{ github.event.comment.user.login }}


      - name: Check Learning Path Links
        id: check-links
        uses: kkeirstead/LearningPathFileChecks@main
        with:
          repoURLToSearch: 'https://github.com/dotnet/dotnet-monitor'
          learningPathsDirectory: 'documentation/learningPath'
          paths: ${{ env.updated_files }}

      - name: Generate artifacts (Suggestion)
        working-directory: ./merge
        run: |
          mkdir -p ./pr
          cp "$GITHUB_EVENT_PATH" ./pr/pr-event.json
          git diff > ./pr/linter.diff
          
      - name: Generate artifacts (Comment)
        working-directory: ./merge
        run: |
          mkdir -p ./learning-path-review
          echo -n "${{ steps.check-links.outputs.result }}" > ./learning-path-review/fileNames

      - name: Upload artifacts (Suggestion)
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce
        with:
          name: pr-linter
          path: merge/pr/

      - name: Upload artifacts (Comment)
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce
        with:
          name: learning-path-review
          path: merge/learning-path-review/
