name: Respond To First Time Issue
on:
  issues:
    types:
      - opened
jobs:
  check-if-new-user:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "# Message with markdown.\nThanks for creating your first issue in the dotnet-monitor repo! Let us know what you think by filling in our [survey](https://aka.ms/dotnet-monitor-survey)."
