name: 'Submit To Do Issue'

on:
  workflow_run:
    workflows: ["Scan For To Do Comments"]
    types:
      - completed

permissions:
  issues: write

jobs:
  submit-todo-issue:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success' && startsWith(github.event.comment.body, '/TODO') && contains(fromJSON('["OWNER", "MEMBER", "COLLABORATOR"]'), github.event.comment.author_association)
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Download the artifact from the workflow that kicked off this one.
      # The default artifact download action doesn't support cross-workflow
      # artifacts, so use a 3rd party one.
      - name: 'Download linting results'
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{env.workflow_name}}
          run_id: ${{github.event.workflow_run.id }}
          name: issue-todo
          path: ./issue-todo
      - run: |
          title=$(cat ./issue-todo/issue-title)
          user=$(cat ./issue-todo/issue-user)
          url=$(cat ./issue-todo/issue-url)
          gh issue create --label "todo" --assignee "$user" --title "$title" --body "$url"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
