name: 'Submit To Do Comments'

on:
  workflow_run:
    workflows: ["To Do Comments"]
    types:
      - completed

permissions:
  issues: write

jobs:
  create-todo-issue:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: |
          title=$(cat ./pr-todo/pr-title)
          user=$(cat ./pr-todo/pr-user)
          url=$(cat ./pr-todo/pr-url)
          gh issue create --label "todo" --assignee "$user" --title "$title" --body "$url"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
