name: To Do Comments
on:
  pull_request_review_comment:
    types: [created]
  issue_comment:
    types: [created]

jobs:
  create-todo-issue:
    runs-on: ubuntu-latest
    if: startsWith(github.event.comment.body, '/TODO') && contains(fromJSON('["OWNER", "MEMBER", "COLLABORATOR"]'), github.event.comment.author_association)
    steps:
      - name: Generate artifacts
        run: |
          trimmed_comment=$(echo "${{ github.event.comment.body }}" | sed 's|/TODO ||I')
          mkdir -p ./pr
          echo -n $trimmed_comment > ./pr/pr-title
          echo -n "${{ github.event.comment.html_url }}" > ./pr/pr-url
          echo -n "${{ github.event.comment.user.login }}" > ./pr/pr-user
          git diff > ./pr/linter.diff
