name: To Do Comments
on:
  pull_request_review_comment:
    types: [created]
  issue_comment:
    types: [created]

jobs:
  create-todo-issue:
    runs-on: ubuntu-latest
    if: startsWith(github.event.comment.body, '/TODO') && contains(fromJSON('["OWNER", "MEMBER", "COLLABORATOR"]'), github.event.comment.author_association)
    steps:
      - run: echo "/TODO Issued from a valid user.
